[project]
name = "pilates_fine_tuned"
version = "0.1.0"
description = "A fine-tuned pilates project."
dependencies = [
    "langchain-huggingface>=0.0.6"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta" 